### ISSUE TITLE
error with example with Python 3.9.2

### ISSUE THREAD

**Issue by egonw** [rinikerlab/lightweight-registration#1]
I following the instructions in the README and the initdb works fine. The next step goes wrong:

```
$ lwreg register --smiles CCOCC
Traceback (most recent call last):
  File "/home/egonw/.local/bin/lwreg", line 33, in <module>
    sys.exit(load_entry_point('lwreg', 'console_scripts', 'lwreg')())
  File "/home/egonw/.local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/egonw/.local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/egonw/.local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/egonw/.local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/egonw/.local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/egonw/var/Projects/hub/lightweight-registration/lwreg/lwreg.py", line 81, in register
    return utils.register(**kwargs)
  File "/home/egonw/var/Projects/hub/lightweight-registration/lwreg/utils.py", line 260, in register
    mrn = _register_mol(tpl, escape, cn, curs, config, fail_on_duplicate)
  File "/home/egonw/var/Projects/hub/lightweight-registration/lwreg/utils.py", line 192, in _register_mol
    mhash, layers = hash_mol(sMol, escape=escape, config=config)
  File "/home/egonw/var/Projects/hub/lightweight-registration/lwreg/utils.py", line 169, in hash_mol
    layers = RegistrationHash.GetMolLayers(
TypeError: GetMolLayers() got an unexpected keyword argument 'enable_tautomer_hash_v2'
```

**Comment by greglandrum** [comment]
Hi @egonw, this isn't documented (yet), but you need to have the 2023.03.1 version of the RDKit installed.

**Comment by egonw** [comment]
It needs 3.11 and I installed it successfully now.
